"""empty message

Revision ID: 17c73668d664
Revises: 283925ecba70
Create Date: 2017-12-19 16:09:48.099492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c73668d664'
down_revision = '283925ecba70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subtitle', sa.String(length=256), nullable=True))
    op.drop_column('posts', 'sub_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('sub_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('posts', 'subtitle')
    # ### end Alembic commands ###
